package jian.lv;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.greghaskins.spectrum.Spectrum;
import jian.lv.App;
import org.junit.Test;
import org.junit.runner.RunWith;

import static com.greghaskins.spectrum.Spectrum.it;
import static com.greghaskins.spectrum.dsl.specification.Specification.context;
import static com.greghaskins.spectrum.dsl.specification.Specification.describe;
import static org.junit.Assert.*;

@RunWith(Spectrum.class)
public class AppTest {{
    describe("Given an App", () -> {
        context("When it start", () -> {
            it("says greeting", () -> {
                App app = new App();
                assertEquals(app.getGreeting(), "Hello world.");
            });
        });
    });
}}
